#:schema node_modules/wrangler/config-schema.json
# wrangler.toml is used for dev mode
# for production, use the cloudflare dashboard
# empty values are placeholders, replace them with your own values


name = "remix-vite-cf-vx"
compatibility_date = "2023-10-30"
pages_build_output_dir = "./build/client"

[[d1_databases]]
binding = "db"
database_name = ""
database_id = ""
migrations_table = "migrations"
migrations_dir = "migrations/"
